/**
 * 演示容灾兜底数据 — DEMO_MODE 下 LLM 失败时返回的预计算完整响应
 *
 * 数据来源：2020年新冠崩盘的真实 LLM 响应 (DeepSeek, 2026-06-25)
 * 场景：美股10天4次熔断, VIX=82, 全球供应链断裂
 *
 * 此数据确保即使断网/API超时，也能展示完整系统功能。
 */

export const FALLBACK_RESPONSE = {
  success: true,
  version: "v9.5",
  data: {
    news: "2020年3月，新冠疫情全球爆发，美股10天4次熔断，VIX飙升至82，全球供应链断裂，多国封锁。",
    factorVector: {
      factors: [
        {
          category: "liquidity",
          value: -90,
          confidence: 80,
          evidence: "熔断导致流动性枯竭，融资环境急剧恶化，信用紧缩。",
        },
        {
          category: "policy",
          value: 80,
          confidence: 80,
          evidence: "全球央行紧急降息、量化宽松和财政刺激预期强烈，政策支持力度极大。",
        },
        {
          category: "fundamental",
          value: -85,
          confidence: 80,
          evidence: "疫情冲击全球供应链，企业盈利预期大幅下调，经济衰退风险显著。",
        },
        {
          category: "narrative",
          value: 95,
          confidence: 75,
          evidence: "疫情与熔断成为全球焦点，媒体持续报道，形成长期恐慌叙事。",
        },
        {
          category: "uncertainty",
          value: 95,
          confidence: 80,
          evidence: "疫情发展、政策效果、经济恢复路径高度不确定。",
        },
      ],
      metadata: {
        newsSummary:
          "2020年3月，新冠疫情全球爆发，美股10天4次熔断，VIX飙升至82",
        detectedAnomalies: [],
        timestamp: "2026-06-25T00:00:00.000Z",
      },
    },
    rounds: [
      {
        round: 1,
        consensus: 1.64,
        direction: "NEUTRAL",
        confidence: 15,
        beliefStd: 85.3,
        neutralTrace: {
          rule1_fired: false,
          rule2_fired: true,
          rule3_fired: true,
          rule4_fired: true,
          finalNeutral: true,
          gatingReason: "R2∧R3:分歧+失同步",
        },
        agents: {
          institution: {
            belief: -20,
            confidence: 57,
            visibleFactors: ["liquidity", "policy", "fundamental"],
            interpretation: "policy↑80 liquidity↓90 fundamental↓85 U:95",
          },
          value: {
            belief: -102,
            confidence: 80,
            visibleFactors: ["fundamental"],
            interpretation: "fundamental↓85 U:95",
          },
          trend: {
            belief: 97,
            confidence: 62,
            visibleFactors: ["narrative"],
            interpretation: "narrative↑95 U:95",
          },
          panic: {
            belief: -104,
            confidence: 39,
            visibleFactors: ["liquidity"],
            interpretation: "liquidity↓90 U:95",
          },
          quant: {
            belief: -78,
            confidence: 70,
            visibleFactors: ["liquidity", "fundamental"],
            interpretation: "liquidity↓90 fundamental↓85 U:95",
          },
          media: {
            belief: 88,
            confidence: 63,
            visibleFactors: ["policy", "narrative"],
            interpretation: "policy↑80 narrative↑95 U:95",
          },
          contrarian: {
            belief: 71,
            confidence: 84,
            visibleFactors: ["narrative"],
            interpretation: "narrative↑95 U:95",
          },
          retail: {
            belief: 104,
            confidence: 45,
            visibleFactors: ["narrative"],
            interpretation: "narrative↑95 U:95",
          },
          policy: {
            belief: 0,
            confidence: 65,
            visibleFactors: ["policy", "liquidity"],
            interpretation: "policy↑80 liquidity↓90 U:95",
          },
        },
      },
      {
        round: 2,
        consensus: 1.64,
        direction: "NEUTRAL",
        confidence: 15,
        beliefStd: 85.3,
        neutralTrace: {
          rule1_fired: false,
          rule2_fired: true,
          rule3_fired: true,
          rule4_fired: true,
          finalNeutral: true,
          gatingReason: "R2∧R3:分歧+失同步",
        },
        agents: {
          institution: {
            belief: -20,
            confidence: 57,
            visibleFactors: ["liquidity", "policy", "fundamental"],
            interpretation: "policy↑80 liquidity↓90 fundamental↓85",
          },
          value: {
            belief: -102,
            confidence: 80,
            visibleFactors: ["fundamental"],
            interpretation: "fundamental↓85",
          },
          trend: {
            belief: 97,
            confidence: 62,
            visibleFactors: ["narrative"],
            interpretation: "narrative↑95",
          },
          panic: {
            belief: -104,
            confidence: 39,
            visibleFactors: ["liquidity"],
            interpretation: "liquidity↓90",
          },
          quant: {
            belief: -78,
            confidence: 70,
            visibleFactors: ["liquidity", "fundamental"],
            interpretation: "liquidity↓90 fundamental↓85",
          },
          media: {
            belief: 88,
            confidence: 63,
            visibleFactors: ["policy", "narrative"],
            interpretation: "policy↑80 narrative↑95",
          },
          contrarian: {
            belief: 71,
            confidence: 84,
            visibleFactors: ["narrative"],
            interpretation: "narrative↑95",
          },
          retail: {
            belief: 104,
            confidence: 45,
            visibleFactors: ["narrative"],
            interpretation: "narrative↑95",
          },
          policy: {
            belief: 0,
            confidence: 65,
            visibleFactors: ["policy", "liquidity"],
            interpretation: "policy↑80 liquidity↓90",
          },
        },
      },
    ],
    final: {
      consensus: 1.64,
      direction: "NEUTRAL",
      confidence: 15,
      beliefStd: 85.3,
      neutralTrace: {
        rule1_fired: false,
        rule2_fired: true,
        rule3_fired: true,
        rule4_fired: true,
        finalNeutral: true,
        gatingReason: "R2∧R3:分歧+失同步",
      },
    },
    ablationMetrics: {
      policyAgentActive: true,
      uncertaintyActive: true,
      blindnessActive: true,
      beliefStdHistory: [85.3, 85.3],
    },
    diagnostics: {
      attribution: [
        {
          agentId: "panic",
          agentName: "Panic",
          emoji: "😱",
          belief: -104,
          confidence: 39,
          influenceWeight: 25,
          contribution: -1014,
          contributionPct: 27,
          direction: "BEARISH",
          visibleFactors: ["liquidity"],
        },
        {
          agentId: "value",
          agentName: "Value",
          emoji: "💎",
          belief: -102,
          confidence: 80,
          influenceWeight: 60,
          contribution: -4896,
          contributionPct: 26,
          direction: "BEARISH",
          visibleFactors: ["fundamental"],
        },
        {
          agentId: "retail",
          agentName: "Retail",
          emoji: "🐜",
          belief: 104,
          confidence: 45,
          influenceWeight: 10,
          contribution: 468,
          contributionPct: 14,
          direction: "BULLISH",
          visibleFactors: ["narrative"],
        },
        {
          agentId: "trend",
          agentName: "Trend",
          emoji: "🏄",
          belief: 97,
          confidence: 62,
          influenceWeight: 45,
          contribution: 2706,
          contributionPct: 13,
          direction: "BULLISH",
          visibleFactors: ["narrative"],
        },
        {
          agentId: "media",
          agentName: "Media",
          emoji: "📡",
          belief: 88,
          confidence: 63,
          influenceWeight: 70,
          contribution: 3881,
          contributionPct: 12,
          direction: "BULLISH",
          visibleFactors: ["policy", "narrative"],
        },
        {
          agentId: "contrarian",
          agentName: "Contrarian",
          emoji: "🦉",
          belief: 71,
          confidence: 84,
          influenceWeight: 40,
          contribution: 2386,
          contributionPct: 7,
          direction: "BULLISH",
          visibleFactors: ["narrative"],
        },
        {
          agentId: "quant",
          agentName: "Quant",
          emoji: "🤖",
          belief: -78,
          confidence: 70,
          influenceWeight: 55,
          contribution: -3003,
          contributionPct: 5,
          direction: "BEARISH",
          visibleFactors: ["liquidity", "fundamental"],
        },
        {
          agentId: "institution",
          agentName: "Institution",
          emoji: "🏦",
          belief: -20,
          confidence: 57,
          influenceWeight: 90,
          contribution: -1026,
          contributionPct: 4,
          direction: "BEARISH",
          visibleFactors: ["liquidity", "policy", "fundamental"],
        },
        {
          agentId: "policy",
          agentName: "PolicyAgent",
          emoji: "🏛️",
          belief: 0,
          confidence: 65,
          influenceWeight: 50,
          contribution: 0,
          contributionPct: 0,
          direction: "NEUTRAL",
          visibleFactors: ["policy", "liquidity"],
        },
      ],
      coalition: {
        bullishCoalition: {
          agentIds: ["trend", "media", "contrarian", "retail"],
          totalInfluence: 165,
          totalCapital: 140,
          weightedBelief: 90,
        },
        bearishCoalition: {
          agentIds: ["institution", "value", "panic", "quant"],
          totalInfluence: 230,
          totalCapital: 290,
          weightedBelief: -66,
        },
        neutralAgents: ["policy"],
        powerRatio: 0.72,
        dominantCoalition: "BEARISH",
        tension: 100,
        swingAgents: ["institution"],
      },
      counterfactuals: {
        baselineConsensus: 1.64,
        variants: [],
        mostInfluentialAgent: "value",
        agentsToFlip: 2,
      },
      summary: {
        coreFinding:
          "共识1.6，方向模糊。Agent信念高度分散(std=85.3)，市场处于极度不确定状态。😱 Panic是NEUTRAL共识的最大驱动力(贡献27%)。尽管BULLISH联盟影响力更大(2.56:1)，但空头少数派信念更强。",
        consensusMechanism:
          "分歧僵局: 多空双方各执一词。多头以叙事驱动(Retail+Trend+Media+Contrarian)，空头以基本面驱动(Value+Panic+Quant)。摇摆Agent Institution(-20)可能决定最终方向。",
        riskFactors: [
          "⚠️ 多空对抗激烈(强度=100)——共识可能在压力下快速瓦解",
          "🔴 系统韧性低: 仅需移除2个Agent即可翻转共识方向",
          "🟡 信息盲区效应显著: 关闭盲区后共识大幅偏移",
        ],
        blindnessEffect:
          "🔴 信息盲区是关键: 关闭盲区后共识方向显著改变。叙事Agent和基本面Agent看到的是完全不同的世界——盲区正在产生真实而深刻的视角分化。",
      },
    },
    v9_5: {
      interaction: {
        totalRounds: 5,
        convergenceType: "diverged",
        rounds: [
          {
            round: 0,
            beliefs: {
              institution: -20,
              value: -102,
              trend: 97,
              panic: -104,
              quant: -78,
              media: 88,
              contrarian: 71,
              retail: 104,
              policy: 0,
            },
            beliefChanges: {},
            meanBelief: 6.2,
            beliefStd: 85.3,
            converged: false,
          },
          {
            round: 1,
            beliefs: {
              institution: -18,
              value: -97,
              trend: 85,
              panic: -80,
              quant: -65,
              media: 75,
              contrarian: 85,
              retail: 90,
              policy: 5,
            },
            beliefChanges: {
              institution: 2,
              value: 5,
              trend: -12,
              panic: 24,
              quant: 13,
              media: -13,
              contrarian: 14,
              retail: -14,
              policy: 5,
            },
            meanBelief: 8.9,
            beliefStd: 79.2,
            converged: false,
          },
          {
            round: 5,
            beliefs: {
              institution: 15,
              value: -55,
              trend: 42,
              panic: -20,
              quant: -15,
              media: 38,
              contrarian: 55,
              retail: 45,
              policy: 28,
            },
            beliefChanges: {
              institution: 3,
              value: 6,
              trend: -5,
              panic: 12,
              quant: 6,
              media: -6,
              contrarian: -4,
              retail: -5,
              policy: 3,
            },
            meanBelief: 14.8,
            beliefStd: 38.5,
            converged: false,
          },
        ],
        beliefShift: {
          institution: 35,
          value: 47,
          trend: -55,
          panic: 84,
          quant: 63,
          media: -50,
          contrarian: -16,
          retail: -59,
          policy: 28,
        },
        consensusFormed: false,
        polarizationIncreased: false,
        socialProfiles: [
          {
            agentId: "institution",
            alpha: 0.15,
            visibleAgentIds: ["value", "panic", "quant", "policy"],
          },
          {
            agentId: "value",
            alpha: 0.05,
            visibleAgentIds: ["institution", "quant"],
          },
          {
            agentId: "trend",
            alpha: 0.5,
            visibleAgentIds: ["media", "contrarian", "retail"],
          },
          {
            agentId: "panic",
            alpha: 0.7,
            visibleAgentIds: ["institution", "quant", "policy"],
          },
          {
            agentId: "quant",
            alpha: 0.1,
            visibleAgentIds: ["institution", "value", "panic", "policy"],
          },
          {
            agentId: "media",
            alpha: 0.45,
            visibleAgentIds: [
              "institution",
              "trend",
              "contrarian",
              "retail",
              "policy",
            ],
          },
          {
            agentId: "contrarian",
            alpha: -0.15,
            visibleAgentIds: ["trend", "media", "retail"],
          },
          {
            agentId: "retail",
            alpha: 0.6,
            visibleAgentIds: ["trend", "media", "contrarian"],
          },
          {
            agentId: "policy",
            alpha: 0.2,
            visibleAgentIds: ["institution", "panic", "quant", "media"],
          },
        ],
      },
      metrics: {
        consensusScore: 48,
        polarizationScore: 78,
        fragilityScore: 65,
        stateLabel: "🔴 两极对抗",
        stateInterpretation:
          "Agent群体分裂为两个势均力敌的对立阵营。共识极度脆弱——任何微小的信息扰动都可能导致方向翻转。市场处于临界状态。",
      },
      comparison: {
        consensusShift: 8.6,
        stdChange: -46.8,
        effect: "convergence",
        description:
          "互动促使Agent信念收敛(std 85→38)。社交影响正在大幅减少观点多样性——但45点的残余分歧仍然是结构性的。",
      },
    },
    v9_5Agents: [
      { id: "institution", name: "Institution", emoji: "🏦", role: "机构投资者" },
      { id: "value", name: "Value", emoji: "💎", role: "价值投资者" },
      { id: "trend", name: "Trend", emoji: "🏄", role: "趋势交易者" },
      { id: "panic", name: "Panic", emoji: "😱", role: "恐慌投资者" },
      { id: "quant", name: "Quant", emoji: "🤖", role: "量化基金" },
      { id: "media", name: "Media", emoji: "📡", role: "媒体传播者" },
      { id: "contrarian", name: "Contrarian", emoji: "🦉", role: "逆向投资者" },
      { id: "retail", name: "Retail", emoji: "🐜", role: "散户投资者" },
      { id: "policy", name: "PolicyAgent", emoji: "🏛️", role: "政策响应分析师" },
    ],
  },
};
